---
inherit_from: <%= "https://#{ENV['CERNER_GITHUB_API_TOKEN']}@raw.github.cerner.com/Igneous/open-rubocop/master/igneous-rubocop.yml" %>
AllCops:
  TargetRubyVersion: 2.6


# ------------------------------------------------------- Style --------------------------------------------------------

Performance/ChainArrayAllocation:
  Enabled: false
