#!/bin/bash

new_file="$1_table.md"
rm "$new_file" 2> /dev/null
file="$1"
created=0
while IFS= read -r line
do
  if [[ ! "$line" =~ ^.*\|.*\|.*$ ]]; then
    if [[ created -eq 1 ]]; then
      echo >> "$new_file"
    fi
    continue
  fi

  if [[ "$created" -eq 0 ]]; then
    touch "$new_file"
    created=1
    pwd
  fi

  echo "$line" >> "$new_file"

done <"$file"

# regex:
# ^ *\|?\[?`?([^\|`\[\]]*)`?\]?\|([^\|]+)\|\[?`?([^\|`\[\]]+)`?\]?[^\|]+\|(.+)$
# replace:
# "    - name: $1\n      type: string\n      in: query\n      description: $3: $4<br>Required: $2"
